### ISSUE TITLE
BUG (monorepo): Package dependencies aren't included when root level dep also exists.

### ISSUE THREAD

**Issue by pdeona** [FormidableLabs/serverless-jetpack#53]
Hi! Awesome package you have here :)

Created a minimal example repo reproducing the issue we are experiencing [here](https://github.com/pdeona/sls-jetpack-issue)

Currently, when 2 functions in our monorepo have conflicting dependencies declared, `serverless-jetpack` is failing to include the `node_modules` that includes the dependency if it is not the root `node_modules`. So for example:

```tree
functions/a/              # depends on diff ^4.0.1
  package.json
  src/
    index.js
  node_modules/
    diff/
functions/b/              # depends on diff @3.5.0
  package.json
  src/
    index.js
node_modules/
  diff/
```

Results in the following artifacts:

```
a/ # no node_modules present
  functions/a/src/index.js
  functions/a/package.json
  package.json
b/ # root node_modules present
  node_modules
  functions/b/src/index.js
  functions/b/package.json
  package.json
```

I can spend some time digging into this issue this weekend, but wanted to open up the issue with an example/description so if anyone else wants to look into it they have some reference info.

**Details**
`serverless-jetpack` version: `^0.5.0`
`serverless` version: `^1.48.0`

/cc @ryan-roemer 

edit:

was able to narrow down the source of the issue:

```
# global include
package:
  individually: true
  include:
    - package.json
    - "!**/yarn.lock"
    - "!functions/**" # this negative include comes after the function-level dependencies in the globInclude array
```

**Comment by ryan-roemer** [comment]
Great reproduction! Issue is verified and I'm working on test fixtures for both npm + yarn + lerna + workspaces here: https://github.com/FormidableLabs/serverless-jetpack/compare/bug/monorepo-deps

Once I've fine tuned the regression test, I'll dig in to fix things. Hopefully a couple days at most! 🤞

**Comment by pdeona** [comment]
some logging revealed an issue in `utils/bundle.js:42-44`, the presence of `!functions/**` in the service include causes all the function level dependencies found in the glob to be turned false in `filesMap`, so they are filtered from the zip

**Comment by ryan-roemer** [comment]
Looking good!

One thing I've messed up is `monorepo/yarn` is different from `monorepo/npm` (needing yarn benchmark:build` to sync). The `yarn` one controls. Should we have this option set now?

```yml
    # Functions (Use specific function includes)
    - '!functions'
    - '!functions/**'
```

or just

```yml
    # Functions (Use specific function includes)
    - '!functions'
```

?

Feel free to experiment and commit in this branch to sync them up and I'll handle the test failures (which is caused by npm + lerna being different than yarn + lerna + workspaces).  Aim for what we should do for the big project we're on 😉 

If you don't have time, I'll pick up tomorrow afternoon -- given your results and diff I'm getting more and more confident about the depInclude move..

**Comment by pdeona** [comment]
good call out - i completely missed that i needed to add that back into the sls config for testing the monorepo scenario (i started a new branch to try the depInclude as an arg to filter files approach). i had to make some more changes, but now it's failing all integration cases due to missing `node_modules/.bin` files in the artifact. i think i should be able to fix that without having to make too many more changes, and hopefully we will have something mergeable soon. let me know if you see something obvious in my latest changes that may be causing the `.bin` exclusion if you have a chance to look over my last commit.

**Comment by ryan-roemer** [comment]
Update: I've been working on various experiments for a "simple approach" and haven't got a complete solution yet. I've enhanced the test cases (to cover more things we're likely to break vs serverless built-in) in https://github.com/FormidableLabs/serverless-jetpack/compare//bug/monorepo-deps...bug/monorepo-deps-2

**Comment by ryan-roemer** [comment]
# SUPER WEIRD STUFF

On a hunch, I decided to cut out all of jetpack and just focus on our `globby()` and `nanomatch` inputs and outputs. I created: [tmp-glob-test.js](https://github.com/FormidableLabs/serverless-jetpack/blob/bug/monorepo-deps-2/tmp-glob-test.js)

Here's the weird stuff: If the working directory matches the "set working directory" internally to jetpack (which is then passed to `globby()` via `cwd) then **different globbing behavior happens**.

Here's a basic example:

```sh
# Start in project root.
# NOTE: `functions/base/node_modules/diff/lib/index.js` is INCLUDED in fileMatch
# which is the `globby()` results.
$ node tmp-glob-test.js 
{
  "fileMatch": {
    "included": [
      "functions/base/node_modules/diff/lib/index.js",
      "functions/base/src/base.js"
    ],
    "excluded": [
      "functions/base/node_modules/another/README.md",
      "functions/base/node_modules/another/index.js",
      "functions/base/node_modules/diff/README.md",
      "functions/base/package.json",
      "functions/base/src/exclude-me.js"
    ]
  },
  "patternMatchLimited": {
    "included": [
      "functions/base/node_modules/diff/lib/index.js",
      "functions/base/src/base.js"
    ],
    "excluded": []
  },
  "patternMatch": {
    "included": [
      "functions/base/node_modules/another/README.md",
      "functions/base/node_modules/another/index.js",
      "functions/base/node_modules/diff/README.md",
      "functions/base/node_modules/diff/lib/index.js",
      "functions/base/package.json",
      "functions/base/src/base.js"
    ],
    "excluded": [
      "functions/base/src/exclude-me.js"
    ]
  }
}

# Move to our test fixture directory that **is** `cwd` in the script
$ cd test/packages/monorepo/yarn/

# NOTE: `functions/base/node_modules/diff/lib/index.js` is EXCLUDED in fileMatch
# which is the `globby()` results.
$ node ../../../../tmp-glob-test.js
{
  "fileMatch": {
    "included": [
      "functions/base/src/base.js"
    ],
    "excluded": [
      "functions/base/node_modules/another/README.md",
      "functions/base/node_modules/another/index.js",
      "functions/base/node_modules/diff/README.md",
      "functions/base/node_modules/diff/lib/index.js",
      "functions/base/package.json",
      "functions/base/src/exclude-me.js"
    ]
  },
  "patternMatchLimited": {
    "included": [
      "functions/base/src/base.js"
    ],
    "excluded": []
  },
  "patternMatch": {
    "included": [
      "functions/base/node_modules/another/README.md",
      "functions/base/node_modules/another/index.js",
      "functions/base/node_modules/diff/README.md",
      "functions/base/node_modules/diff/lib/index.js",
      "functions/base/package.json",
      "functions/base/src/base.js"
    ],
    "excluded": [
      "functions/base/src/exclude-me.js"
    ]
  }
}
```

# Takeaways

- If we're not `process.cwd() === cwd` then a simple `!functions` (and not `!functions/**`) gets us pretty much what we want for our monorepo scenario -- exclude all of `functions` except for things added back in **and** the dependencies added by Jetpack.
- I'm going to look for an upstream issue in `globby()` to see if there's some insight into this behavior. It seems super weird that `globby(patterns, { cwd })` has that parameter but the **actual** current working directory affects results...

**Comment by pdeona** [comment]
that is odd, and a quick look at globby indicates the issue may be even further upstream because they just pass the options object to `fast-glob` after doing some stuff with ignore patterns

**Comment by ryan-roemer** [comment]
Yep! I instrumented (_cough, cough added a lot of `console.log`_) `globby()` and the same inputs around the `fast-glob` calls yield different outputs. Basically I did this:

```js
	const paths = await Promise.all(tasks.map(task => {
		// TODO console.log("TODO GLOBBY", { task })
		return fastGlob(task.pattern, task.options).then((files) => {
			// console.log("TODO GLOBBY", {
			// 	task,
			// 	files
			// });
			return files;
		})
	}));
```

Next step is digging into `fast-glob` calls and checking how `cwd` is actually handled...

**Comment by ryan-roemer** [comment]
Here's the difference in fast-glob inputs / outputs:

```js
function getWorks(source, _Provider, options) {
    const patterns = [].concat(source);
    const settings = new settings_1.default(options);
    const tasks = taskManager.generate(patterns, settings);
    console.log("TODO HERE fast-glob", { patterns, options, tasks });
    const provider = new _Provider(settings);
    return tasks.map(provider.read, provider);
}
```

Not `process.cwd() === cwd`

```js
TODO HERE fast-glob { patterns: [ 'functions/base/node_modules/diff/**' ],
  options: 
   { ignore: 
      [ 'functions/base/node_modules/diff/node_modules',
        '**/.DS_Store',
        '**/yarn.lock',
        '**/package-lock.json',
        '**/node_modules/{@*/*,*}/CHANGELOG.md',
        '**/node_modules/{@*/*,*}/HISTORY.md',
        '**/node_modules/{@*/*,*}/LICENSE',
        '**/node_modules/{@*/*,*}/README.md',
        'functions/**', // <== THIS HAS ** APPENDED
        'functions/**/exclude-me.js' ],
     expandDirectories: true,
     cwd: '/Users/rye/scm/fmd/serverless-jetpack/test/packages/monorepo/yarn',
     dot: true,
     silent: true,
     follow: true,
     nodir: true },
  tasks: 
   [ { dynamic: true,
       positive: [Array],
       negative: [Array],
       base: 'functions/base/node_modules/diff',
       patterns: [Array] } ] }
```

vs. `process.cwd() !== cwd`

```js
TODO HERE fast-glob { patterns: [ 'functions/base/node_modules/diff/**' ],
  options: 
   { ignore: 
      [ 'functions/base/node_modules/diff/node_modules',
        '**/.DS_Store',
        '**/yarn.lock',
        '**/package-lock.json',
        '**/node_modules/{@*/*,*}/CHANGELOG.md',
        '**/node_modules/{@*/*,*}/HISTORY.md',
        '**/node_modules/{@*/*,*}/LICENSE',
        '**/node_modules/{@*/*,*}/README.md',
        'functions', // <== THIS DOESN'T
        'functions/**/exclude-me.js' ],
     expandDirectories: true,
     cwd: '/Users/rye/scm/fmd/serverless-jetpack/test/packages/monorepo/yarn',
     dot: true,
     silent: true,
     follow: true,
     nodir: true },
  tasks: 
   [ { dynamic: true,
       positive: [Array],
       negative: [Array],
       base: 'functions/base/node_modules/diff',
       patterns: [Array] } ] }
```

**Comment by pdeona** [comment]
hmm, so maybe globby’s logic for generating ignores is off here - we are not passing anything to the ignore option in jetpack iirc, but it does pass in negative includes right?

**Comment by ryan-roemer** [comment]
I've been going back and forth all week, I'd like to hash out my current "best" idea.

My starting point:

- We're pretty stuck with the `globby() + include` and then `nanomatch() + exclude + include` in terms of blanket exclusion patterns like `!functions/**` in a monorepo scenario.
- There are some hacky things we can do, but even my experiment above relies on non-obvious behavior between `!function` vs `!function/**`
- We want to maintain "drop in" compatibility with `serverless package`

*How Jetpack currently works*

For background, here's what jetpack does:

1. `globby()` phase: Use patterns of `**` + Jetpack-inferred dependency patterns (`depInclude`) + Serverless normal config `include` to read of disk into a list of files.
2. `nanomatch()` phase: Take the list of files and apply Serverless normal config `exclude` and then `include`.

*PROPOSAL: New Jetpack config*

The idea here is we need "something" to go before Jetpack dependency patterns that can blanketly nuke `!functions/**` in a disk efficient manner, which means during the `globby()` phase. Here's one way:

New configuration support:

```yml
# serverless.yml
custom:
  jetpack:
    preInclude:
      # Added before Jetpack dependencies and sls `include`
      - "!functions"
      - "!functions/**"

package:
  include:
    # General exclusions
    - "!**/.DS_Store"
    - "!**/yarn.lock"
    - "!**/package-lock.json"

functions:
  base:
    handler: functions/base/src/base.handler
    jetpack:
      roots:
        - functions/base
    package:
      include:
        - "functions/base/src/**"
```

which would translate to the following in `globby()` phase:

```yml
- "**"
# preInclude
- "!functions"
- "!functions/**"
# Jetpack dynamic dependencies
- "functions/base/node_modules/diff"
- ...
# Sls includes (service and function)
- "!**/.DS_Store"
- "!**/yarn.lock"
- "!**/package-lock.json"
- "functions/base/src/**"
```

And tweak the logic to be something like:

1. `globby()` phase: Use patterns of `**` + Jetpack-custom `preInclude` + Jetpack-inferred dependency patterns (`depInclude`) + Serverless normal config `include` to read of disk into a list of files.
2. `nanomatch()` phase: Take the list of files and apply Serverless normal config `exclude` and then Jetpack-custom `preInclude` + Jetpack-inferred dependency patterns (`depInclude`) +`include`.

... and I think that gets us all the way there for our common monorepo scenario. There are more details as to why the above would happen, but I'm thinking of working in branch-of-branch to compartmentalize this work.

Good things from this approach:

- Without `jetpack.preInclude` normal behavior stays absolutely the same, we maintain dorp-in compatibility.
- It's probably only monorepo folks who need `preInclude` now, but that's likely OK to require Jetpack-specific-customizations since you already need to use `jetpack.roots` if you have a monorepo. So, most non-monorepo scenarios won't need any jetpack-specific changes.

Thoughts @pdeona @mscottx88 ? Thanks!

**Comment by pdeona** [comment]
that sounds like a good approach! the greatest difficulty i encountered trying to fix this was maintaining the existing functionality for non-monorepos so adding a new config option may very well be required. as you said there is no equivalent sls behavior in the monorepo scenario so needing a little extra in our config to get it to work seems fine.
